-- Add is_ai_response column to chat_messages table
ALTER TABLE public.chat_messages
ADD COLUMN IF NOT EXISTS is_ai_response BOOLEAN DEFAULT false;

-- Create index for faster AI message queries
CREATE INDEX IF NOT EXISTS chat_messages_is_ai_response_idx 
ON public.chat_messages(is_ai_response);

-- Create AI agent settings table for future configuration
CREATE TABLE IF NOT EXISTS public.ai_agent_settings (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  ai_enabled BOOLEAN DEFAULT true,
  auto_respond BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT ai_agent_settings_pkey PRIMARY KEY (id),
  CONSTRAINT ai_agent_settings_user_id_unique UNIQUE (user_id)
);

-- Enable Row Level Security
ALTER TABLE public.ai_agent_settings ENABLE ROW LEVEL SECURITY;

-- Create policy for users to manage their own AI settings
CREATE POLICY "Users can manage their own AI settings"
ON public.ai_agent_settings
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Add comment for documentation
COMMENT ON COLUMN public.chat_messages.is_ai_response IS 'Indicates if this message was generated by the AI agent';
COMMENT ON TABLE public.ai_agent_settings IS 'Stores AI agent preferences per user';
